// StudioInk content — generated by admin panel
// HOW TO USE:
//   1. Keep this file in the SAME folder as studioink.html and admin.html
//   2. After publishing articles in admin.html, a new content.js downloads automatically
//   3. Save/replace this file with the downloaded one — studioink.html updates instantly
//   4. No server needed. Works from any drive (K:, USB, local, etc.)
//
// This starter file contains the default articles.
// It will be replaced each time you export from admin.html.

window.STUDIOINK_CONTENT = {
  "generatedAt": "2026-04-09T00:00:00.000Z",
  "articleCount": 6,
  "articles": [
    {
      "id": 0,
      "title": "The invisible grid: how leading shapes reading",
      "excerpt": "Line spacing is the most powerful and most overlooked typographic tool. Here\u2019s what the masters knew that we keep forgetting in the age of auto.",
      "category": "typography",
      "author": "Maya Kim",
      "status": "published",
      "date": "2026-04-04",
      "reads": 1240,
      "likes": 88,
      "comments": 14,
      "readTime": "8 min",
      "tags": ["Typography", "Leading", "Readability"],
      "body": "<h2>The invisible architecture of text</h2><p>Open any design textbook and you\u2019ll find chapters on typeface selection, font pairing, and hierarchy. Leading \u2014 the space between lines \u2014 rarely gets more than a paragraph. Yet leading is the invisible grid that either lets text breathe or chokes it to death.</p><blockquote><p>Good typography is invisible. The reader doesn\u2019t notice it \u2014 they just find the text easy, even pleasurable, to read.</p></blockquote><h2>What the masters knew</h2><p>Jan Tschichold understood that line height wasn\u2019t decoration \u2014 it was structure. He prescribed leading as a function of typeface design, measure (line length), and reading distance.</p><ul><li>Body text typically needs 120\u2013145% leading</li><li>Display type can go tighter \u2014 even 90% in all-caps settings</li><li>Small text (under 12px) often needs 150% or more</li></ul><h2>Digital degrades leading</h2><p>CSS\u2019s <code>line-height: 1.5</code> has become the default across the web \u2014 a compromise that works reasonably for nothing and brilliantly for nothing. The magic number doesn\u2019t exist. Leading is a design decision.</p>"
    },
    {
      "id": 1,
      "title": "Hierarchy without size: weight, space, and restraint",
      "excerpt": "Every student reaches for a larger font to create hierarchy. Here\u2019s how the professionals do it with subtlety and precision.",
      "category": "typography",
      "author": "Maya Kim",
      "status": "published",
      "date": "2026-04-02",
      "reads": 740,
      "likes": 64,
      "comments": 9,
      "readTime": "6 min",
      "tags": ["Typography", "Hierarchy", "Weight"],
      "body": "<h2>The tyranny of scale</h2><p>When students first learn typographic hierarchy, they reach for the most obvious tool: size. But professional typographers know that hierarchy can be established through weight, spacing, and position alone, with far more nuance.</p><blockquote><p>Restraint is not weakness. It is the hardest skill to develop and the clearest signal of mastery.</p></blockquote><h2>Weight as signal</h2><p>A semibold heading at the same size as body text, set above a hairline rule, communicates hierarchy without shouting. The relationship is established through contrast of weight, not scale.</p>"
    },
    {
      "id": 2,
      "title": "Why your color palette keeps failing in production",
      "excerpt": "Palettes that look beautiful in Figma collapse in code. The culprit is almost always context, not color.",
      "category": "color",
      "author": "James Reyes",
      "status": "published",
      "date": "2026-03-28",
      "reads": 980,
      "likes": 112,
      "comments": 21,
      "readTime": "10 min",
      "tags": ["Color", "Production", "Figma"],
      "body": "<h2>The context problem</h2><p>You\u2019ve built a gorgeous palette. Then development starts and everything falls apart. Colors that were harmonious in your design file look flat, muddy, or clashing in the browser.</p><blockquote><p>Color has no meaning in isolation. Every color is changed by everything around it.</p></blockquote><h2>Simultaneous contrast</h2><p>Josef Albers demonstrated that color perception is entirely relational. A gray appears cool on a warm background and warm on a cool one. When you test a palette in a design file, you\u2019re testing it against white \u2014 the default background of every design tool.</p>"
    },
    {
      "id": 3,
      "title": "Negative space is not empty space",
      "excerpt": "The space between elements is as active as the elements themselves. Learning to design the voids transforms composition.",
      "category": "layout",
      "author": "Sara Naomi",
      "status": "published",
      "date": "2026-03-20",
      "reads": 820,
      "likes": 97,
      "comments": 18,
      "readTime": "9 min",
      "tags": ["Layout", "Composition", "Whitespace"],
      "body": "<h2>What fills the gaps</h2><p>Beginning designers fill space. Experienced designers do the opposite: they remove elements until what remains is essential, and then they work on the quality of what\u2019s left \u2014 the voids.</p><blockquote><p>In music, the rests are as important as the notes. In design, the space is as active as the form.</p></blockquote><h2>The figure-ground relationship</h2><p>Gestalt psychology gave us the vocabulary: figure and ground. The figure is the object we attend to; the ground is everything else. But ground is not passive \u2014 it can become figure.</p>"
    },
    {
      "id": 4,
      "title": "The mark without meaning: why logomarks fail",
      "excerpt": "Clever logomarks are everywhere. Memorable ones are rare. The difference is almost never visual.",
      "category": "branding",
      "author": "James Reyes",
      "status": "published",
      "date": "2026-03-25",
      "reads": 620,
      "likes": 55,
      "comments": 7,
      "readTime": "7 min",
      "tags": ["Branding", "Logo", "Identity"],
      "body": "<h2>Cleverness is not meaning</h2><p>Today\u2019s design culture has confused clever with meaningful. The dual-meaning logo, the letterform hidden in negative space \u2014 these tricks abound, but most are forgotten within a year of launch.</p><blockquote><p>A logo is not a brand. It is a vessel that the brand fills over time.</p></blockquote><h2>What meaning actually is</h2><p>Meaning in a mark isn\u2019t encoded in the shape \u2014 it accumulates through use. The Nike swoosh meant nothing when it was designed in 1971.</p>"
    },
    {
      "id": 5,
      "title": "Design critique: how to give feedback that builds",
      "excerpt": "Critique is a skill. Most designers were never taught it. Here\u2019s a framework for making feedback genuinely useful.",
      "category": "ux",
      "author": "Sara Naomi",
      "status": "published",
      "date": "2026-03-15",
      "reads": 560,
      "likes": 73,
      "comments": 24,
      "readTime": "7 min",
      "tags": ["Process", "Critique", "Feedback"],
      "body": "<h2>The failure of I like/I don\u2019t like</h2><p>Most design critique is conducted through preference. This feedback is nearly useless \u2014 it tells the designer nothing about why, and it conflates personal taste with design judgment.</p><blockquote><p>Good critique is generous: it assumes the designer made intelligent choices and asks what those choices were trying to achieve.</p></blockquote><h2>A criteria-based framework</h2><p>Effective critique is criteria-based. Before evaluating work, establish what the work is trying to accomplish \u2014 the problem it solves, the audience it serves, the constraints it operates within.</p>"
    }
  ],
  "paths": [
    {"id":0,"name":"Typography Fundamentals","level":"Beginner","articles":12,"enrolled":1840,"status":"active","desc":"Master the core principles of type."},
    {"id":1,"name":"Grid Systems Mastery","level":"Intermediate","articles":9,"enrolled":1240,"status":"active","desc":"From baseline to modular grids."},
    {"id":2,"name":"Color Theory in Practice","level":"All levels","articles":11,"enrolled":2100,"status":"active","desc":"How color communicates and fails."},
    {"id":3,"name":"Brand Identity Design","level":"Intermediate","articles":15,"enrolled":980,"status":"active","desc":"Build identities that endure."},
    {"id":4,"name":"UX Writing & Hierarchy","level":"Beginner","articles":8,"enrolled":760,"status":"active","desc":"Words are design."},
    {"id":5,"name":"Design Systems at Scale","level":"Advanced","articles":14,"enrolled":640,"status":"draft","desc":"Token architecture and governance."}
  ]
};
